### ISSUE TITLE
cannot identify image file 'img_a.jpg'](url)

### ISSUE THREAD

**Issue by MurageKabui** [Python-Nairobi/ImPro#2]
Are all the camera links down or is it on my side only ? 
This is what I'm getting.. 
```
[
Traceback (most recent call last):
  File "C:\Users\kabue\Desktop\ImPro-master\ImPro-master\main.py", line 34, in <module>
    x = traffic.load()
  File "C:\Users\kabue\Desktop\ImPro-master\ImPro-master\image_processing.py", line 62, in load
    a[names] = Image.open(names).convert('L')
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2657, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'img_a.jpg'](url)
```

**Comment by MurageKabui** [comment]
the images pulled appear to be blank 
does it still work?
